apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mobsf-deployment
spec:
  selector:
    matchLabels:
      app: mobsf
  replicas: 1 # only run 1 pod
  template:
    metadata:
      labels:
        app: mobsf
    spec:
      volumes:
      - name: data-volume
        hostPath: 
          path: /mnt/volume_lon1_01/BBS/output/private/extra-mobsf/
          type: DirectoryOrCreate 
      containers:
      - name: mobsf
        image: opensecurity/mobile-security-framework-mobsf   
        volumeMounts:
        - name: data-volume
          mountPath: /root/.MobSF
        ports:
        - containerPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: mobsf-service
spec:
  selector:
    app: mobsf
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  internalTrafficPolicy: Local
