apiVersion: v1
kind: ConfigMap
metadata:
  name: crtsh-configmap
data:     
  crt.sh: |-
    #!/bin/sh
    fetch() {
      curl -s https://crt.sh/?Identity=%.$1 | grep ">*.$1" | sed 's/<[/]*[TB][DR]>/\n/g' | grep -vE "<|^[\*]*[\.]*$1" | sort -u | awk 'NF'
    }
    if [ $DATA_DIR ] 
    then
      echo "[i] Log data in $DATA_DIR/$( date +"%Y-%m-%d")_$1.crtsh.out"
      [ ! -d $DATA_DIR ] && mkdir -p $DATA_DIR
      fetch $1 | tee -a $DATA_DIR/$( date +"%Y-%m-%d")_$1.crtsh.out
      sort -u $DATA_DIR/$( date +"%Y-%m-%d")_$1.crtsh.out -o $DATA_DIR/$( date +"%Y-%m-%d")_$1.crtsh.out
      # Consolidate with existing results
      echo [i] colsolidate results in $DATA_DIR/$( date +"%Y-%m-%d")_$1.out
      cat $DATA_DIR/$( date +"%Y-%m-%d")_$1.crtsh.out >> $DATA_DIR/$( date +"%Y-%m-%d")_$1.out
      sort -u $DATA_DIR/$( date +"%Y-%m-%d")_$1.out -o $DATA_DIR/$( date +"%Y-%m-%d")_$1.out  
    else
      fetch $1
    fi

---
apiVersion: batch/v1
kind: Job
metadata:
  name: crtsh-BBS_PROJECT_CODE
  labels:
    app: crtsh-BBS_PROJECT_CODE
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: crtsh-BBS_PROJECT_CODE
    spec:
      volumes:
      - name: data-volume
        hostPath: 
          path: /mnt/volume_lon1_01
          type: Directory
      - name: configmap-volume
        configMap:
          name: crtsh-configmap
          defaultMode: 0755 
      containers:
      - name: crtsh-BBS_PROJECT_CODE
        image: smokingcaterpillar/bbs-osintel-gau-subs
        volumeMounts:
        - name: data-volume
          mountPath: /optdata
        - name: configmap-volume
          mountPath: /opt/crtsh
        command: 
        - /bin/bash
        - -c
        - |
          echo crtsh v1
          echo Code: BBS_PROJECT_CODE
          echo Id: BBS_PROJECT_ID
          echo List: BBS_PROJECT_LIST
          
          ## BBRF SETUP ##
          echo setting up BBRF...
          cp /optdata/BBS/output/private/bbrs-config.json /root/.bbrf/config.json
          bbrf use BBS_PROJECT_CODE
          ## BBRF SETUP ##
          
          
          cd /optdata/BBS
          
          
          mkdir -p output/project-data/BBS_PROJECT_CODE/data/osintel/crtsh/
          cd output/project-data/BBS_PROJECT_CODE/data/osintel/crtsh/
          mkdir -p /optdata/BBS/output/project-data/BBS_PROJECT_CODE/data/osintel/crtsh/data/$HOSTNAME/

      
          echo running crt.sh...
          cd /optdata/BBS/output/project-data/BBS_PROJECT_CODE/data/osintel/crtsh/data/$HOSTNAME/
          DATA_DIR="/optdata/BBS/output/project-data/BBS_PROJECT_CODE/data/osintel/crtsh/data/$HOSTNAME/"
          echo reading list items
          counter=0
          input="/optdata/BBS/output/project-data/BBS_PROJECT_CODE/scope/generated/inscope.wildcard-domains.txt"
          while IFS= read -r line
          do
            echo Running crt.sh on "$line"
            domainname=`echo http://$line | unfurl format %r.%t`
            echo looking up $domainname
            bash /opt/crtsh/crt.sh $domainname            
            counter=$((counter+1))
          done < "$input"         
                    
          echo all done
      restartPolicy: Never

