apiVersion: batch/v1
kind: Job
metadata:
  name: domain2ip-BBS_PROJECT_CODE
  labels:
    app: domain2ip-BBS_PROJECT_CODE
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: domain2ip-BBS_PROJECT_CODE
    spec:
      volumes:
      - name: data-volume
        hostPath: 
          path: /mnt/volume_lon1_01
          type: Directory
      containers:
      - name: domain2ip-BBS_PROJECT_CODE
        image: smokingcaterpillar/bbs-osintel-github-subs
        volumeMounts:
        - name: data-volume
          mountPath: /optdata
        command: 
        - /bin/bash
        - -c
        - |
          echo domain2ip v1
          echo Code: BBS_PROJECT_CODE
          echo Id: BBS_PROJECT_ID
          echo List: BBS_PROJECT_LIST
       
          
          ## BBRF SETUP ##
          echo setting up BBRF...
          cp /optdata/BBS/output/private/bbrs-config.json /root/.bbrf/config.json
          bbrf use BBS_PROJECT_CODE
          ## BBRF SETUP ##
          
          echo installing dnsx
          GO111MODULE=on go get -v github.com/projectdiscovery/dnsx/cmd/dnsx
          
          bbrf domains --view unresolved | dnsx -silent -a -resp | tr -d '[]' | tee \
            >(awk '{print $1":"$2}' | bbrf domain update - -s dnsx) \
            >(awk '{print $1":"$2}' | bbrf domain add - -s dnsx) \
            >(awk '{print $2":"$1}' | bbrf ip add - -s dnsx) \
            >(awk '{print $2":"$1}' | bbrf ip update - -s dnsx)
          
          echo all done
      restartPolicy: Never

