apiVersion: batch/v1
kind: Job
metadata:
  name: bbs-debug-BBS_PROJECT_CODE
  labels:
    app: bbs-debug-BBS_PROJECT_CODE
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: bbs-debug-BBS_PROJECT_CODE
    spec:
      volumes:
      - name: data-volume
        hostPath: 
          path: /mnt/volume_lon1_01
          type: Directory
      containers:
      - name: bbs-debug-BBS_PROJECT_CODE
        image: smokingcaterpillar/bbs-osintel-github-subs
        volumeMounts:
        - name: data-volume
          mountPath: /optdata
        command: 
        - /bin/sh
        - -c
        - |
          echo Debug v1
          echo Code: BBS_PROJECT_CODE
          echo Id: BBS_PROJECT_ID
          echo List: BBS_PROJECT_LIST
          
          ## BBRF SETUP ##
          echo setting up BBRF...
          cp /optdata/BBS/output/private/bbrs-config.json /root/.bbrf/config.json
          bbrf use BBS_PROJECT_CODE
          ## BBRF SETUP ##
          
          mkdir -p /optdata/BBS/output/project-data/BBS_PROJECT_CODE/data/debug/
          
          echo dumping scope in
          bbrf scope in > /optdata/BBS/output/project-data/BBS_PROJECT_CODE/data/debug/scope.in.txt
          echo dumping scope out
          bbrf scope out > /optdata/BBS/output/project-data/BBS_PROJECT_CODE/data/debug/scope.out.txt
          echo ""
          echo dumping domains
          bbrf domains > /optdata/BBS/output/project-data/BBS_PROJECT_CODE/data/debug/domains.txt
          echo ""
          echo dumping ips
          bbrf ips > /optdata/BBS/output/project-data/BBS_PROJECT_CODE/data/debug/ips.txt
          echo ""
          echo dumping urls
          bbrf urls > /optdata/BBS/output/project-data/BBS_PROJECT_CODE/data/debug/urls.txt
          echo ""
                    
          echo all done
      restartPolicy: Never

