apiVersion: batch/v1
kind: Job
metadata:
  name: arjun-BBS_PROJECT_CODE
  labels:
    app: arjun-BBS_PROJECT_CODE
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: arjun-BBS_PROJECT_CODE
    spec:
      volumes:
      - name: data-volume
        hostPath: 
          path: /mnt/volume_lon1_01
          type: Directory
      containers:
      - name: arjun-BBS_PROJECT_CODE
        image: smokingcaterpillar/bbs-osintel-gau-subs
        volumeMounts:
        - name: data-volume
          mountPath: /optdata
        command: 
        - /bin/bash
        - -c
        - |
          echo arjun v1
          echo Code: BBS_PROJECT_CODE
          echo Id: BBS_PROJECT_ID
          echo List: BBS_PROJECT_LIST
          
          ## BBRF SETUP ##
          echo setting up BBRF...
          cp /optdata/BBS/output/private/bbrs-config.json /root/.bbrf/config.json
          bbrf use BBS_PROJECT_CODE
          ## BBRF SETUP ##
          
          
          cd /optdata/BBS
          
          
          mkdir -p output/project-data/BBS_PROJECT_CODE/data/scanner/arjun/
          cd output/project-data/BBS_PROJECT_CODE/data/scanner/arjun/
          
          echo Installing arjun...
          pip3 install arjun
          
      
          echo running arjun...
          arjun -oT arjun.txt -i /optdata/BBS/output/project-data/BBS_PROJECT_CODE/BBS_PROJECT_LIST -c 100 --stable  > arjun.log.txt
          
          
                    
          echo all done
      restartPolicy: Never

