apiVersion: batch/v1
kind: Job
metadata:
  name: meg-BBS_PROJECT_CODE
  labels:
    app: meg-BBS_PROJECT_CODE
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: meg-BBS_PROJECT_CODE
    spec:
      volumes:
      - name: data-volume
        hostPath: 
          path: /mnt/volume_lon1_01
          type: Directory
      containers:
      - name: meg-BBS_PROJECT_CODE
        image: smokingcaterpillar/bbs-osintel-gau-subs
        volumeMounts:
        - name: data-volume
          mountPath: /optdata
        command: 
        - /bin/bash
        - -c
        - |
          echo meg v1
          echo Code: BBS_PROJECT_CODE
          echo Id: BBS_PROJECT_ID
          echo List: BBS_PROJECT_LIST
          
          ## BBRF SETUP ##
          echo setting up BBRF...
          cp /optdata/BBS/output/private/bbrs-config.json /root/.bbrf/config.json
          bbrf use BBS_PROJECT_CODE
          ## BBRF SETUP ##
          
          
          cd /optdata/BBS
          
          
          mkdir -p output/project-data/BBS_PROJECT_CODE/data/scanner/meg/
          cd output/project-data/BBS_PROJECT_CODE/data/scanner/meg/
          
          
          go get -u github.com/tomnomnom/meg
          
          meg --verbose paths /optdata/BBS/output/project-data/BBS_PROJECT_CODE/BBS_PROJECT_LIST 
          
          
                    
          echo all done
      restartPolicy: Never

